// Generated data, DO NOT MODIFY HERE.
// Check the `data_extractors` folder in the AP World source code at
// https://github.com/Satisha10/Archipelago_wotw/tree/alabaster-dawn/worlds/alabaster_dawn/data_extractors
// to see how to generate this file or to make modifications.
// This file got generated in `item_maps.py` with `item_gamename_map`."""

type ItemData = {
    name: string;
    qty: number;
}

export const item_name_data = new Map<string, ItemData>([
    ["Test", {name: "test", qty: 1}],
    ["Physis", {name: "ELEMENT_NATURE", qty: 1}],
    ["Aether", {name: "ELEMENT_AETHER", qty: 1}],
    ["Sword", {name: "WEAPON:sword", qty: 1}],
    ["Hammer", {name: "WEAPON:hammer", qty: 1}],
    ["Crossbow", {name: "WEAPON:crossbow", qty: 1}],
    ["Chakram", {name: "WEAPON:chakram", qty: 1}],
    ["Kama", {name: "WEAPON:kama", qty: 1}],
    ["Filia", {name: "PARTY:filia", qty: 1}],
    ["Lyhamn level", {name: "todo", qty: 1}],
    ["Valley bridges repaired", {name: "todo2", qty: 1}],
    ["Low tide", {name: "todo3", qty: 1}],
    ["Boat travel", {name: "todo4", qty: 1}],
    ["Fulcrum Mark", {name: "the-key", qty: 1}],
    ["Trial Mark", {name: "the-key-dng", qty: 1}],
    ["Whisper of the gods x5", {name: "chest-ess-1-whisper", qty: 5}],
    ["Verse of the Gods", {name: "chest-ess-2-verse", qty: 3}],
    ["Sphera Essence x5", {name: "ball-ess", qty: 5}],
    ["Arma Sphera Essence x5", {name: "ess-armor-ball", qty: 5}],
    ["Pilo Sphera Essence x5", {name: "ess-hair-ball", qty: 5}],
    ["Vespa Essence x5", {name: "wasp-ess", qty: 5}],
    ["Turri Essence x5", {name: "flower-ess", qty: 5}],
    ["Custo Turri Essence x5", {name: "guard-flower-ess", qty: 5}],
    ["Ericius Essence x3", {name: "ess-hedgebird", qty: 3}],
    ["Testudo Essence x3", {name: "ess-turtle", qty: 3}],
    ["Rana Essence x5", {name: "ess-frog", qty: 5}],
    ["Pendicis Essence x3", {name: "ess-flyfish", qty: 3}],
    ["Aranea Mu Essence", {name: "ess-common-spider", qty: 1}],
    ["Algae Dolus Essence x5", {name: "ess-algae", qty: 5}],
    ["Molis Essence x3", {name: "ess-molerat", qty: 3}],
    ["Papilium Essence x3", {name: "ess-butterflybird", qty: 3}],
    ["Bovarks Essence x3", {name: "ess-bowcow", qty: 3}],
    ["Carota Essence x5", {name: "ess-evil-garrot", qty: 5}],
    ["Pullu Essence x5", {name: "ess-bamboo", qty: 5}],
    ["Fern Essence x5", {name: "ess-water-plant", qty: 5}],
    ["Crista Essence x5", {name: "ess-hexa-plant", qty: 5}],
    ["Curcur Essence x5", {name: "ess-pumpkin", qty: 5}],
    ["Chipped Edge", {name: "mel-str-01", qty: 1}],
    ["Bent Edge", {name: "mel-crit-01", qty: 1}],
    ["Ruff Edge", {name: "mel-spec-01", qty: 1}],
    ["Shaggy Quill", {name: "rng-str-01", qty: 1}],
    ["Fickle Quill", {name: "rng-crit-01", qty: 1}],
    ["Dirty Quill", {name: "rng-spec-01", qty: 1}],
    ["Dim Halo", {name: "up-maj-l-def-01", qty: 1}],
    ["Vexed Halo", {name: "up-maj-l-off-01", qty: 1}],
    ["Spirit Laurel", {name: "up-maj-r-def-01", qty: 1}],
    ["Crude Laurel", {name: "up-maj-r-off-01", qty: 1}],
    ["Flexing Bracer", {name: "mid-maj-l-off-01", qty: 1}],
    ["Stiff Bracer", {name: "mid-maj-l-def-01", qty: 1}],
    ["Ruffian's Gauntlet", {name: "mid-maj-r-off-01", qty: 1}],
    ["Plebian Gauntlet", {name: "mid-maj-r-def-01", qty: 1}],
    ["Brittle Shell", {name: "low-maj-l-def-01", qty: 1}],
    ["Light Shell", {name: "low-maj-l-off-01", qty: 1}],
    ["Simple Cuirass", {name: "low-maj-r-def-01", qty: 1}],
    ["Runner's Cuirass", {name: "low-maj-r-off-01", qty: 1}],
    ["Blood Eye Construct", {name: "bp-mel-min-aff", qty: 1}],
    ["Shatter End Construct", {name: "bp-mel-min-breaker", qty: 1}],
    ["Amplifier Construct", {name: "bp-mel-min-ampli", qty: 1}],
    ["Finishing Touch Construct", {name: "bp-mel-finisher", qty: 1}],
    ["Double Trouble Construct", {name: "bp-mel-brkdmg", qty: 1}],
    ["Distant Mark Construct", {name: "bp-rang-min-snip", qty: 1}],
    ["High Ground Construct", {name: "bp-rang-min-highground", qty: 1}],
    ["Fly Swatter Construct", {name: "bp-rng-min-wing", qty: 1}],
    ["Stem Pecker Construct", {name: "bp-rng-min-root", qty: 1}],
    ["Bully Construct", {name: "bp-rng-min-bul", qty: 1}],
    ["Steady Zeal Construct", {name: "bp-rng-min-dp", qty: 1}],
    ["Verdant Guard Construct", {name: "bp-cor-min-defl", qty: 1}],
    ["Libra's Blessing Construct", {name: "bp-cor-min-aether", qty: 1}],
    ["Blood Heart Construct", {name: "bp-cor-min-crit", qty: 1}],
    ["Tireless Boulder Construct", {name: "bp-cor-min-stam", qty: 1}],
    ["Lucky Reflex Construct", {name: "bp-cor-min-critdef", qty: 1}],
    ["Feline's Gaze Construct", {name: "bp-cor-min-hazdef", qty: 1}],
    ["Grit Construct", {name: "bp-cor-min-grit", qty: 1}],
    ["Cleanse Construct", {name: "bp-cor-min-balance", qty: 1}],
    ["Bramble Quake", {name: "phy-mel-grass1", qty: 1}],
    ["Verdant Saw", {name: "phy-mel-grass2", qty: 1}],
    ["Leaf Blades", {name: "phy-rgd-status1", qty: 1}],
    ["Cragspike Salvo", {name: "phy-rgd-dps1", qty: 1}],
    ["Ring of Rocks", {name: "phy-grd-shield1", qty: 1}],
    ["Boom Snare", {name: "aet-mel-aoe1", qty: 1}],
    ["Zapflash Slash", {name: "aet-mel-dps1", qty: 1}],
    ["Crack Shock", {name: "aet-rgd-status1", qty: 1}],
    ["Bolt Barrage", {name: "aet-rgd-beam1", qty: 1}],
    ["Stardrop Counter", {name: "aet-grd-evadeAtk", qty: 1}],
]);
